Repository ipython/ipykernel, pull requests merged in 2021-11, with the labels that each got.

#794 Automated Changelog Entry for 6.5.0 on master
  CHANGELOG.md
Labels: documentation

#801 fix #800 the temp file name generated by murmur2 in python and ts is not same
  ipykernel/compiler.py
Labels: bug

#803 Enforce labels on PRs
  .github/workflows/enforce-label.yml
Labels: maintenance

#804 Automated Changelog Entry for 6.5.1 on master
  CHANGELOG.md
Labels: documentation

#807 Add explicit encoding to open calls in debugger
  ipykernel/debugger.py
Labels: maintenance

#808 Remove Nose dependency
  ipykernel/tests/test_kernel.py
  ipykernel/tests/utils.py
  setup.py
Labels: maintenance

#809 Send omit_sections to IPython to choose which sections of documentation you don't want
  ipykernel/ipkernel.py
  ipykernel/kernelbase.py
Labels: enhancement

#812 Set debugOptions for breakpoints in python standard library source
  ipykernel/debugger.py
Labels: enhancement
