Repository ipython/ipykernel, pull requests merged in 2021-03, with the labels that each got.

#597 Implementation of the debugger
  .github/workflows/ci.yml
  ipykernel/compiler.py
  ipykernel/control.py
  ipykernel/debugger.py
  ipykernel/heartbeat.py
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/kernelspec.py
  setup.py
Labels: enhancement

#610 Move Python-specific bits to ipkernel
  ipykernel/ipkernel.py
  ipykernel/kernelbase.py
Labels: enhancement

#617 Follow up DeprecationWarning Fix
  ipykernel/ipkernel.py
Labels: bug

#620 Update changelog for 5.5.2
  docs/changelog.rst
Labels: docs

#623 Changelog for 5.5.3
  docs/changelog.rst
Labels: docs

#625 Run GitHub Actions on all branches
  .github/workflows/ci.yml
Labels: enhancement

#624 Implemented inspectVariables request
  ipykernel/debugger.py
Labels: enhancement

#627 Update Trio mode for compatibility with Trio >= 0.18.0
  ipykernel/trio_runner.py
Labels: bug
