Repository ipython/ipykernel, pull requests merged in 2021-09, with the labels that each got.

#765 Fix undefined variable
  ipykernel/debugger.py
Labels: bug

#708 Make json_clean a no-op for jupyter-client >= 7
  ipykernel/datapub.py
  ipykernel/debugger.py
  ipykernel/inprocess/ipkernel.py
  ipykernel/jsonutil.py
  ipykernel/tests/test_jsonutil.py
Labels: enhancement

#766 Don't assume kernels have loops.
  ipykernel/zmqshell.py
Labels: bug

#767 Make ipykernel work without debugpy
  .github/workflows/ci.yml
  ipykernel/ipkernel.py
  ipykernel/kernelspec.py
Labels: maintenance

#769 Automated Changelog Entry for 6.4.0 on master
  CHANGELOG.md
Labels: documentation

#774 Automated Changelog Entry for 6.4.1 on master
  CHANGELOG.md
Labels: documentation
