Repository ipython/ipykernel, pull requests merged in 2021-07, with the labels that each got.

#704 Fix Tk and asyncio event loops
  ipykernel/eventloops.py
Labels: bug

#703 Update changelog for 6.0.1
  CHANGELOG.md
Labels: documentation

#709 [bugfix] fix in setup.py (comma before appnope)
  setup.py
Labels: bug

#710 Remove CachingCompiler's filename_mapper
  ipykernel/compiler.py
Labels: maintenance

#711 Fix typo in eventloops.py
  ipykernel/eventloops.py
Labels: bug

#723 Replace non-existing function.
  ipykernel/ipkernel.py
Labels: maintenance

#722 Remove unused variables
  ipykernel/kernelbase.py
  ipykernel/tests/test_embed_kernel.py
  ipykernel/tests/test_kernel.py
  ipykernel/tests/test_kernelspec.py
  ipykernel/tests/test_message_spec.py
  ipykernel/tests/test_start_kernel.py
Labels: maintenance

#721 Do not use bare except
  ipykernel/comm/comm.py
  ipykernel/comm/manager.py
  ipykernel/debugger.py
  ipykernel/eventloops.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/parentpoller.py
Labels: maintenance

#719 Formatting: remove semicolon
  ipykernel/debugger.py
Labels: maintenance

#718 Clean most flake8 unused import warnings.
  docs/conf.py
  ipykernel/comm/manager.py
  ipykernel/connect.py
  ipykernel/debugger.py
  ipykernel/inprocess/channels.py
  ipykernel/inprocess/socket.py
  ipykernel/inprocess/tests/test_kernelmanager.py
  ipykernel/jsonutil.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/log.py
  ipykernel/pickleutil.py
  ipykernel/pylab/backend_inline.py
  ipykernel/pylab/config.py
  ipykernel/tests/test_pickleutil.py
  ipykernel/tests/test_zmq_shell.py
  ipykernel/tests/utils.py
Labels: maintenance

#720 misc whitespace and line too long
  examples/embedding/ipkernel_qtapp.py
  examples/embedding/ipkernel_wxapp.py
  ipykernel/_eventloop_macos.py
  ipykernel/debugger.py
  ipykernel/eventloops.py
  ipykernel/ipkernel.py
  ipykernel/tests/test_kernelspec.py
  ipykernel/zmqshell.py
Labels: maintenance

#717 Minimal flake8 config
  setup.cfg
Labels: maintenance

#727 Add watchfd keyword to InProcessKernel OutStream initialization
  ipykernel/inprocess/ipkernel.py
Labels: bug

#728 Add changelog for 6.0.2
  CHANGELOG.md
Labels: documentation

#731 RFC: kernelapp: rename ports variable to avoid override
  ipykernel/kernelapp.py
Labels: bug

#733 Add changelog for 6.0.3
  CHANGELOG.md
Labels: documentation

#734 Implemented richInspectVariable request handler
  ipykernel/debugger.py
Labels: enhancement
