Repository ipython/ipykernel, pull requests merged in 2021-06, with the labels that each got.

#683 Make the isatty method of OutStream return True
  ipykernel/iostream.py
  ipykernel/tests/test_io.py
Labels: enhancement

#684 call metadata methods on abort replies
  ipykernel/kernelbase.py
Labels: bug

#685 Return len of item written to OutStream
  ipykernel/iostream.py
Labels: bug

#687 Remove `ipykernel.codeutil` deprecated since IPykernel 4.3.1 (Feb 2016)
  ipykernel/codeutil.py
  ipykernel/pickleutil.py
  ipykernel/tests/test_serialize.py
  setup.py
Labels: maintenance

#688 Remove deprecated profile options of connect.py
  CHANGELOG.md
  ipykernel/connect.py
Labels: maintenance

#689 Remove deprecated SocketABC since 4.5.0
  ipykernel/inprocess/socket.py
Labels: maintenance

#690 Remove deprecated source parameter since 4.0.1 (2015)
  ipykernel/zmqshell.py
Labels: maintenance

#686 Misc Updates to changelog for 6.0
  CHANGELOG.md
Labels: documentation

#573 Deacrease lag time for eventloop
  ipykernel/kernelbase.py
Labels: bug

#692 Remove pin on Jedi because that was already fixed in IPython
  setup.py
Labels: maintenance

#695 Remove references to deprecated ipyparallel
  ipykernel/tests/test_serialize.py
  ipykernel/zmqshell.py
Labels: bug

#698 Update Changelog for 6.0 Release
  CHANGELOG.md
Labels: documentation

#702 stringify variables that are not json serializable in inspectVariable…
  ipykernel/debugger.py
Labels: bug
