Repository ipython/ipykernel, pull requests merged in 2021-08, with the labels that each got.

#738 bump importlib-metadata limit for python<3.8
  setup.py
Labels: maintenance

#739 Update changelog for 6.1
  CHANGELOG.md
Labels: documentation

#736 Remove block param from get_msg()
  ipykernel/tests/test_embed_kernel.py
  ipykernel/tests/test_kernel.py
  ipykernel/tests/test_start_kernel.py
  ipykernel/tests/utils.py
  setup.py
Labels: maintenance

#741 Add Support for Message Based Interrupt
  ipykernel/kernelbase.py
  ipykernel/tests/test_kernel.py
Labels: enhancement

#743 Remove some more dependency on nose/iptest
  ipykernel/tests/test_kernel.py
Labels: maintenance

#745 Set up release helper plumbing
  .github/workflows/check-release.yml
  CHANGELOG.md
  MANIFEST.in
  RELEASE.md
  ipykernel/_version.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#748 Remove Nose skipIf in favor of pytest
  ipykernel/tests/test_message_spec.py
Labels: maintenance

#747 remove more nose
  ipykernel/tests/test_kernelspec.py
Labels: maintenance

#635 Test downstream projects
  .github/workflows/downstream.yml
Labels: maintenance

#750 Remove more nose test references
  README.md
  ipykernel/tests/test_io.py
  ipykernel/tests/test_jsonutil.py
  ipykernel/tests/test_message_spec.py
  setup.cfg
  setup.py
Labels: maintenance

#753 Implemented deep variable inspection
  ipykernel/debugger.py
Labels: enhancement

#754 Automated Changelog Entry for 6.3.0 on master
  CHANGELOG.md
Labels: documentation

#757 Automated Changelog Entry for 6.3.1 on master
  CHANGELOG.md
Labels: documentation
