Repository ipython/ipykernel, pull requests merged in 2021-04, with the labels that each got.

#631 Make less use of ipython_genutils
  ipykernel/ipkernel.py
  ipykernel/zmqshell.py
Labels: maintenance

#634 Use channel get_msg helper method
  ipykernel/inprocess/client.py
  ipykernel/inprocess/tests/test_kernel.py
  ipykernel/tests/test_kernel.py
  ipykernel/tests/test_message_spec.py
  ipykernel/tests/utils.py
Labels: maintenance

#638 make deprecated shell_streams writable
  ipykernel/ipkernel.py
  ipykernel/kernelbase.py
Labels: maintenance

#644 Build docs only on ubuntu : add jobs to check docstring formatting.
  .github/workflows/ci.yml
  ipykernel/kernelspec.py
  ipykernel/pickleutil.py
Labels: documentation, maintenance

#632 Use native coroutines instead of tornado coroutines
  ipykernel/inprocess/client.py
  ipykernel/inprocess/ipkernel.py
  ipykernel/ipkernel.py
  ipykernel/kernelbase.py
Labels: maintenance

#652 Allow setting cell name
  ipykernel/compiler.py
Labels: enhancement
