Repository ipython/ipykernel, pull requests merged in 2021-12, with the labels that each got.

#813 Test jupyter_kernel_test as downstream
  .github/workflows/downstream.yml
Labels: maintenance

#814 Added missing excpeionPaths field to debugInfo reply
  ipykernel/debugger.py
Labels: bug

#815 Automated Changelog Entry for 6.6.0 on master
  CHANGELOG.md
Labels: documentation

#817 RF: Handle both asyncio.QueueEmpty and tornado.queues.QueueEmpty
  ipykernel/kernelbase.py
Labels: bug

#444 Allow pyside2 gui loop
  ipykernel/eventloops.py
Labels: bug

#820 Clean up workflows
  .github/workflows/check-release.yml
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  ipykernel/tests/test_kernel.py
  ipykernel/tests/utils.py
Labels: maintenance

#822 IPython's start_kernel is deprecated.
  ipykernel/tests/test_start_kernel.py
Labels: maintenance

#827 Clean python 2 artifacts. Fix #826
  examples/embedding/internal_ipkernel.py
  ipykernel/comm/comm.py
  ipykernel/compiler.py
  ipykernel/debugger.py
  ipykernel/displayhook.py
  ipykernel/eventloops.py
  ipykernel/gui/gtk3embed.py
  ipykernel/gui/gtkembed.py
  ipykernel/inprocess/blocking.py
  ipykernel/inprocess/channels.py
  ipykernel/inprocess/client.py
  ipykernel/inprocess/ipkernel.py
  ipykernel/inprocess/manager.py
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/parentpoller.py
  ipykernel/pickleutil.py
  ipykernel/tests/__init__.py
  ipykernel/tests/test_async.py
  ipykernel/tests/test_debugger.py
  ipykernel/tests/test_embed_kernel.py
  ipykernel/tests/test_jsonutil.py
  ipykernel/tests/test_kernel.py
  ipykernel/tests/test_kernelspec.py
  ipykernel/tests/test_message_spec.py
  ipykernel/tests/test_pickleutil.py
  ipykernel/tests/test_zmq_shell.py
  ipykernel/zmqshell.py
Labels: maintenance

#828 Fix title position in changelog
  CHANGELOG.md
Labels: documentation
