Repository ipython/ipykernel, pull requests merged in 2021-05, with the labels that each got.

#591 Use matplotlib-inline
  ipykernel/kernelapp.py
  ipykernel/pylab/backend_inline.py
  ipykernel/pylab/config.py
  ipykernel/zmqshell.py
  setup.py
Labels: enhancement

#654 Import configure_inline_support from matplotlib_inline if available
  .github/workflows/ci.yml
  ipykernel/zmqshell.py
Labels: bug

#655 Add changelog entry for 5.5.4
  docs/changelog.rst
Labels: documentation

#657 Add Kernel.get_parent_header
  ipykernel/comm/comm.py
  ipykernel/kernelbase.py
Labels: maintenance

#669 Keep preferring SelectorEventLoop on Windows
  ipykernel/kernelapp.py
Labels: maintenance

#670 Backport PR #669 on branch 5.5.x (Keep preferring SelectorEventLoop on Windows)
  ipykernel/kernelapp.py
Labels: maintenance

#671 Update changelog for 5.5.5
  docs/changelog.rst
Labels: documentation

#672 Add 5.5.x Changelog entries
  CHANGELOG.md
Labels: documentation

#673 fix keyboard interrupt issue in dispatch_shell
  ipykernel/kernelbase.py
Labels: bug

#674 Backport PR #673 on branch 5.5.x (fix keyboard interrupt issue in dispatch_shell)
  ipykernel/kernelbase.py
Labels: bug
