Repository ipython/ipykernel, pull requests merged in 2022-02, with the labels that each got.

#849 Handle all threads stopped correctly
  ipykernel/control.py
  ipykernel/debugger.py
  ipykernel/heartbeat.py
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/tests/test_debugger.py
Labels: bug

#850 Cancel duplicate runs
  .github/workflows/check-release.yml
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  .github/workflows/enforce-label.yml
Labels: maintenance

#852 Automated Changelog Entry for 6.8.0 on main
  CHANGELOG.md
Labels: documentation

#855 Fixed event forwarding
  ipykernel/debugger.py
Labels: bug

#853 use message queue for abort_queues
  ipykernel/kernelbase.py
  ipykernel/tests/test_message_spec.py
Labels: bug

#858 Automated Changelog Entry for 6.9.0 on main
  CHANGELOG.md
Labels: documentation

#865 Add hostname to the usage reply
  ipykernel/kernelbase.py
Labels: bug

#863 Enable standard library debugging via config
  ipykernel/debugger.py
  ipykernel/ipkernel.py
  ipykernel/kernelbase.py
Labels: bug

#866 Automated Changelog Entry for 6.9.1 on main
  CHANGELOG.md
Labels: documentation

#871 Clean up CI
  .github/workflows/check-release.yml
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
Labels: maintenance

#869 BUG: Kill subprocesses on shutdown.
  ipykernel/kernelbase.py
  setup.py
Labels: bug

#874 Only kill children in process group at shutdown
  ipykernel/debugger.py
  ipykernel/ipkernel.py
  ipykernel/kernelbase.py
  ipykernel/kernelspec.py
  ipykernel/tests/test_kernel.py
  setup.py
Labels: bug

#877 Catch error when shutting down kernel from the control channel
  ipykernel/eventloops.py
Labels: bug
