Repository ipython/ipykernel, pull requests merged in 2022-09, with the labels that each got.

#984 Add python logo in svg format
  ipykernel/resources/logo-svg.svg
Labels: maintenance

#990 PR: Close memory leak
  ipykernel/eventloops.py
Labels: bug

#991 Automated Changelog Entry for 6.15.3 on main
  CHANGELOG.md
Labels: documentation

#994 Remove unused manifest file
  MANIFEST.in
Labels: maintenance

#998 Use hatch for version
  RELEASE.md
  ipykernel/_version.py
  pyproject.toml
Labels: maintenance

#996 Add client 8 support
  ipykernel/inprocess/client.py
Labels: maintenance

#999 Automated Changelog Entry for 6.16.0 on main
  CHANGELOG.md
Labels: documentation
