Repository ipython/ipykernel, pull requests merged in 2022-01, with the labels that each got.

#830 PR: do_one_iteration is a coroutine
  ipykernel/eventloops.py
  setup.py
Labels: bug

#831 Automated Changelog Entry for 6.6.1 on main
  CHANGELOG.md
Labels: documentation

#829 Breakpoint in cell with leading empty lines may be ignored
  ipykernel/debugger.py
  ipykernel/tests/test_debugger.py
Labels: bug

#834 Remove impossible skipif.
  ipykernel/tests/test_async.py
  ipykernel/tests/test_eventloop.py
  ipykernel/tests/test_kernel.py
Labels: maintenance

#835 Remove pipx to fix conflicts
  .github/workflows/ci.yml
  setup.py
Labels: maintenance

#837 Skip on PyPy, seem to fail.
  ipykernel/tests/test_kernel.py
Labels: maintenance

#838 Normalize debugger temp file paths on Windows
  ipykernel/compiler.py
  ipykernel/debugger.py
  ipykernel/tests/test_debugger.py
Labels: bug

#805 Add usage_request and usage_reply based on psutil
  ipykernel/kernelbase.py
Labels: enhancement

#839 Removed DebugStdLib from arguments of attach
  ipykernel/debugger.py
Labels: bug

#843 Automated Changelog Entry for 6.7.0 on main
  CHANGELOG.md
Labels: documentation

#844 Handled AllThreadsContinued and workaround for wrong threadId in cont…
  ipykernel/debugger.py
Labels: bug

#816 Add support for the debug modules request
  ipykernel/debugger.py
Labels: enhancement
