Repository ipython/ipykernel, pull requests merged in 2022-12, with the labels that each got.

#1049 Fix: there can be only one comm_manager
  ipykernel/comm/comm.py
  ipykernel/ipkernel.py
  ipykernel/tests/test_comm.py
  pyproject.toml
Labels: bug

#1051 fix: too many arguments dropped when passing to base comm constructor
  ipykernel/comm/comm.py
  ipykernel/tests/test_comm.py
Labels: bug

#1057 format dates as ISO8601
  ipykernel/jsonutil.py
  ipykernel/tests/test_jsonutil.py
Labels: bug

#1058 Fix lint
  .pre-commit-config.yaml
  examples/embedding/ipkernel_wxapp.py
  ipykernel/embed.py
  ipykernel/gui/gtk3embed.py
  ipykernel/gui/gtkembed.py
  ipykernel/heartbeat.py
  ipykernel/inprocess/channels.py
  ipykernel/inprocess/client.py
  ipykernel/inprocess/ipkernel.py
  ipykernel/inprocess/socket.py
  ipykernel/inprocess/tests/test_kernelmanager.py
  ipykernel/serialize.py
  ipykernel/zmqshell.py
  pyproject.toml
Labels: maintenance

#1056 Fix comms and add qtconsole downstream test
  .github/workflows/downstream.yml
  ipykernel/comm/comm.py
  ipykernel/comm/manager.py
  ipykernel/tests/test_comm.py
Labels: bug, maintenance

#1061 Don't pass `None` kernels to logging configurable in `Comm`
  ipykernel/comm/comm.py
  ipykernel/tests/test_comm.py
Labels: bug

#1063 Add more ci checks
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  docs/conf.py
  examples/embedding/inprocess_qtconsole.py
  examples/embedding/inprocess_terminal.py
  examples/embedding/internal_ipkernel.py
  examples/embedding/ipkernel_qtapp.py
  examples/embedding/ipkernel_wxapp.py
  hatch_build.py
  ipykernel/__main__.py
  ipykernel/comm/comm.py
  ipykernel/comm/manager.py
  ipykernel/compiler.py
  ipykernel/control.py
  ipykernel/datapub.py
  ipykernel/debugger.py
  ipykernel/displayhook.py
  ipykernel/eventloops.py
  ipykernel/gui/gtk3embed.py
  ipykernel/gui/gtkembed.py
  ipykernel/heartbeat.py
  ipykernel/inprocess/blocking.py
  ipykernel/inprocess/channels.py
  ipykernel/inprocess/client.py
  ipykernel/inprocess/ipkernel.py
  ipykernel/inprocess/manager.py
  ipykernel/inprocess/socket.py
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/kernelspec.py
  ipykernel/log.py
  ipykernel/parentpoller.py
  ipykernel/pickleutil.py
  ipykernel/tests/test_message_spec.py
  ipykernel/trio_runner.py
  ipykernel/zmqshell.py
  pyproject.toml
Labels: maintenance

#1054 ENH: add `%gui` support for Qt6
  ipykernel/eventloops.py
  ipykernel/tests/test_eventloop.py
  pyproject.toml
Labels: enhancement
