Repository ipython/ipykernel, pull requests merged in 2022-04, with the labels that each got.

#900 use packaging instead of pkg_resources to parse versions
  ipykernel/eventloops.py
  ipykernel/tests/test_message_spec.py
  setup.py
Labels: enhancement

#902 Make cell_id optional
  ipykernel/inprocess/tests/test_kernel.py
  ipykernel/ipkernel.py
  ipykernel/kernelbase.py
  pyproject.toml
  setup.py
Labels: bug

#903 Automated Changelog Entry for 6.12.0 on main
  CHANGELOG.md
Labels: documentation

#905 Automated Changelog Entry for 6.12.1 on main
  CHANGELOG.md
Labels: documentation

#909 Update setup.py
  setup.py
Labels: maintenance

#911 Clean up pre-commit
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: maintenance

#913 Add basic mypy support
  .pre-commit-config.yaml
  MANIFEST.in
  docs/conf.py
  examples/embedding/inprocess_terminal.py
  ipykernel/_eventloop_macos.py
  ipykernel/_version.py
  ipykernel/connect.py
  ipykernel/debugger.py
  ipykernel/displayhook.py
  ipykernel/eventloops.py
  ipykernel/gui/gtk3embed.py
  ipykernel/gui/gtkembed.py
  ipykernel/heartbeat.py
  ipykernel/inprocess/blocking.py
  ipykernel/inprocess/channels.py
  ipykernel/inprocess/socket.py
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/jsonutil.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/log.py
  ipykernel/parentpoller.py
  ipykernel/pickleutil.py
  ipykernel/py.typed
  ipykernel/serialize.py
  ipykernel/trio_runner.py
  ipykernel/zmqshell.py
  pyproject.toml
  setup.py
Labels: maintenance

#916 Automated Changelog Entry for 6.13.0 on main
  CHANGELOG.md
Labels: documentation

#921 Allow enforce PR label workflow to add labels
  .github/workflows/enforce-label.yml
Labels: maintenance
