Repository ipython/ipykernel, pull requests merged in 2022-03, with the labels that each got.

#879 Automated Changelog Entry for 6.9.2 on main
  CHANGELOG.md
Labels: documentation

#883 Add precision about subprocess stdout/stderr capturing
  CHANGELOG.md
Labels: documentation

#884 Check if the current thread is the io thread
  ipykernel/iostream.py
Labels: bug

#887 More CI cleanup
  .github/workflows/ci.yml
Labels: maintenance

#888 Improve performance of stderr and stdout stream buffer
  ipykernel/iostream.py
Labels: enhancement

#891 Automated Changelog Entry for 6.10.0 on main
  CHANGELOG.md
Labels: documentation

#889 Add pytest opts and pre-commit
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
  .mailmap
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  COPYING.md
  MANIFEST.in
  RELEASE.md
  docs/index.rst
  docs/requirements.txt
  examples/embedding/internal_ipkernel.py
  examples/embedding/ipkernel_qtapp.py
  ipykernel/__init__.py
  ipykernel/comm/manager.py
  ipykernel/debugger.py
  ipykernel/kernelspec.py
  ipykernel/pickleutil.py
  ipykernel/tests/__init__.py
  ipykernel/tests/test_debugger.py
  ipykernel/tests/test_kernelspec.py
  ipykernel/tests/test_pickleutil.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#893 Add ignore-revs file
  .git-blame-ignore-revs
Labels: maintenance

#895 Include method signatures in experimental completion results
  ipykernel/ipkernel.py
Labels: enhancement

#886 Try to pass cell id to executing kernel.
  ipykernel/inprocess/tests/test_kernel.py
  ipykernel/ipkernel.py
  ipykernel/kernelbase.py
Labels: enhancement

#896 Handle warnings in tests
  .github/workflows/ci.yml
  ipykernel/eventloops.py
  ipykernel/tests/conftest.py
  ipykernel/tests/test_embed_kernel.py
  ipykernel/tests/test_message_spec.py
  ipykernel/tests/test_pickleutil.py
  pyproject.toml
  setup.py
Labels: maintenance

#898 Automated Changelog Entry for 6.11.0 on main
  CHANGELOG.md
Labels: documentation

#899 Do not try to send on iostream if closed
  ipykernel/iostream.py
Labels: bug
