Repository ipython/ipykernel, pull requests merged in 2022-06, with the labels that each got.

#943 Fix richInspectVariables
  ipykernel/debugger.py
Labels: bug

#949 Automated Changelog Entry for 6.13.1 on main
  CHANGELOG.md
Labels: documentation

#951 Fix sphinx 5.0 support
  docs/conf.py
Labels: maintenance

#937 Ensure psutil for the process is accurate
  ipykernel/kernelbase.py
Labels: bug

#948 use pss memory info type if available for the resource usage reply
  ipykernel/kernelbase.py
Labels: bug

#953 Automated Changelog Entry for 6.14.0 on main
  CHANGELOG.md
Labels: documentation

#956 Fix compatibility with tornado 6.2 beta
  ipykernel/control.py
  ipykernel/iostream.py
Labels: bug

#957 Explicitly require pyzmq >= 17
  pyproject.toml
Labels: maintenance

#958 Back to top-level tornado IOLoop
  ipykernel/control.py
  ipykernel/iostream.py
Labels: maintenance

#959 Automated Changelog Entry for 6.15.0 on main
  CHANGELOG.md
Labels: documentation
