Repository ipython/ipykernel, pull requests merged in 2022-11, with the labels that each got.

#1017 Add dependabot
  .github/dependabot.yml
Labels: maintenance

#1019 Ignore the new Jupyter_core deprecation warning in CI
  pyproject.toml
Labels: maintenance

#1020 Allow releasing from repo
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  RELEASE.md
Labels: maintenance

#1023 Add windows coverage and clean up workflows
  .github/workflows/check-release.yml
  .github/workflows/ci.yml
  ipykernel/tests/test_embed_kernel.py
  ipykernel/tests/test_eventloop.py
  ipykernel/tests/test_start_kernel.py
  pyproject.toml
Labels: maintenance

#973 Extract the Comm Python package
  ipykernel/comm/__init__.py
  ipykernel/comm/comm.py
  ipykernel/comm/manager.py
  ipykernel/ipkernel.py
  pyproject.toml
Labels: enhancement

#1029 Use base setup dependency type
  .github/workflows/ci.yml
Labels: maintenance

#1028 fix: use comm package in backwards compatible way
  ipykernel/comm/__init__.py
  ipykernel/comm/comm.py
  ipykernel/comm/manager.py
  ipykernel/ipkernel.py
Labels: bug

#1030 Clean up testing and coverage
  .coveragerc
  ipykernel/tests/test_kernel_direct.py
  pyproject.toml
Labels: maintenance

#1031 Add more coverage and add Readme badges
  README.md
  ipykernel/ipkernel.py
  ipykernel/tests/conftest.py
  ipykernel/tests/test_ipkernel_direct.py
  pyproject.toml
Labels: maintenance

#1032 Add more kernel tests
  ipykernel/ipkernel.py
  ipykernel/tests/conftest.py
  ipykernel/tests/test_ipkernel_direct.py
  ipykernel/tests/test_kernel_direct.py
  pyproject.toml
Labels: maintenance

#1034 Add more tests
  ipykernel/iostream.py
  ipykernel/tests/test_io.py
  ipykernel/tests/test_zmq_shell.py
  ipykernel/zmqshell.py
Labels: maintenance

#1035 More coverage improvements
  ipykernel/jsonutil.py
  ipykernel/tests/test_parentpoller.py
  pyproject.toml
Labels: maintenance

#1036 Add more testing and deprecate the Gtk event loops
  ipykernel/comm/comm.py
  ipykernel/gui/gtk3embed.py
  ipykernel/gui/gtkembed.py
  ipykernel/inprocess/tests/test_kernel.py
  ipykernel/kernelapp.py
  ipykernel/tests/test_comm.py
  ipykernel/tests/test_embed_kernel.py
  ipykernel/tests/test_eventloop.py
  ipykernel/tests/test_kernel.py
  ipykernel/tests/test_kernelapp.py
  ipykernel/trio_runner.py
  pyproject.toml
Labels: maintenance

#1037 Configurables needs to be configurable
  ipykernel/ipkernel.py
  ipykernel/tests/test_ipkernel_direct.py
Labels: bug

#1042 Fix Comm interface for downstream users
  .github/workflows/downstream.yml
  ipykernel/comm/comm.py
  ipykernel/comm/manager.py
Labels: bug
