Repository ipython/ipykernel, pull requests merged in 2022-10, with the labels that each got.

#1002 Ignore warnings in prereleases test
  .github/workflows/ci.yml
Labels: maintenance

#1006 Maintenance cleanup
  .flake8
  .github/workflows/check-release.yml
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  docs/conf.py
  docs/requirements.txt
  ipykernel/connect.py
  ipykernel/iostream.py
  ipykernel/tests/test_kernel.py
  pyproject.toml
  readthedocs.yml
Labels: maintenance

#1008 PR: Destroy tk app to avoid memory leak
  ipykernel/eventloops.py
Labels: bug

#1010 Fix failing test and update matrix
  .github/workflows/ci.yml
  ipykernel/tests/test_message_spec.py
Labels: maintenance

#1012 Enable webagg in %matplotlib
  ipykernel/eventloops.py
Labels: enhancement

#1013 Update supported pythons to 3.8-3.11
  .github/workflows/ci.yml
  pyproject.toml
Labels: maintenance

#1014 Add pyupgrade to pre-commit
  .pre-commit-config.yaml
  examples/embedding/internal_ipkernel.py
  ipykernel/eventloops.py
  ipykernel/heartbeat.py
  ipykernel/ipkernel.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/kernelspec.py
  ipykernel/tests/test_kernel.py
  ipykernel/tests/test_message_spec.py
  ipykernel/zmqshell.py
Labels: maintenance
