Repository ipython/ipykernel, pull requests merged in 2023-12, with the labels that each got.

#1177 Refactor execute_request to reduce redundancy and improve consistency
  ipykernel/kernelbase.py
Labels: maintenance

#1178 Update pytest commands in README
  README.md
Labels: documentation

#1099 Adds a flag in debug_info for the copyToGlobals support
  ipykernel/debugger.py
Labels: enhancement

#1184 Enable `ProactorEventLoop` on windows for `ipykernel`
  ipykernel/kernelapp.py
Labels: enhancement

#1185 Support python 3.12
  .github/workflows/ci.yml
  pyproject.toml
Labels: maintenance
