Repository ipython/ipykernel, pull requests merged in 2023-02, with the labels that each got.

#1086 Restore nest-asyncio for tk loop
  ipykernel/eventloops.py
  pyproject.toml
Labels: maintenance

#1084 Remove test_enter_eventloop
  ipykernel/tests/test_kernel_direct.py
Labels: maintenance

#1095 Un-expose __file__ and expose __session__ instead.
  ipykernel/ipkernel.py
Labels: bug

#1098 Add license
  COPYING.md
  LICENSE
  README.md
  ipykernel/gui/__init__.py
  ipykernel/gui/gtk3embed.py
  ipykernel/gui/gtkembed.py
  ipykernel/heartbeat.py
  ipykernel/inprocess/blocking.py
  ipykernel/inprocess/client.py
  pyproject.toml
Labels: maintenance

#1096 Update changelog for markdown typo
  CHANGELOG.md
Labels: documentation
