Repository ipython/ipykernel, pull requests merged in 2023-07, with the labels that each got.

#1134 Clean up lint
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  ipykernel/debugger.py
  ipykernel/pickleutil.py
  pyproject.toml
Labels: maintenance

#1135 feat: let display hook handle clear_output
  ipykernel/zmqshell.py
Labels: enhancement

#1133 Merge connection info into existing connection file if it already exists
  ipykernel/kernelapp.py
  ipykernel/tests/test_ipkernel_direct.py
  ipykernel/tests/test_kernelapp.py
Labels: bug
