Repository ipython/ipykernel, pull requests merged in 2023-05, with the labels that each got.

#1114 Support control<>iopub messages to e.g. unblock comm_msg from command execution
  ipykernel/comm/comm.py
  ipykernel/control.py
Labels: enhancement

#1117 update readthedocs env to 3.11
  .readthedocs.yaml
Labels: maintenance

#1111 Avoid echoing onto a captured FD
  .github/workflows/ci.yml
  ipykernel/iostream.py
  ipykernel/tests/test_io.py
  pyproject.toml
Labels: bug
