Repository ipython/ipykernel, pull requests merged in 2023-01, with the labels that each got.

#1070 Fix types and sync lint deps
  ipykernel/inprocess/tests/test_kernel.py
  ipykernel/ipkernel.py
  ipykernel/kernelapp.py
  ipykernel/tests/test_kernel.py
  ipykernel/tests/test_zmq_shell.py
  ipykernel/zmqshell.py
  pyproject.toml
Labels: maintenance

#1073 Update CI
  .pre-commit-config.yaml
  ipykernel/connect.py
  ipykernel/eventloops.py
  ipykernel/inprocess/channels.py
  ipykernel/inprocess/client.py
  ipykernel/inprocess/manager.py
  ipykernel/iostream.py
  ipykernel/jsonutil.py
  ipykernel/kernelbase.py
  ipykernel/parentpoller.py
  ipykernel/trio_runner.py
  ipykernel/zmqshell.py
  pyproject.toml
Labels: maintenance

#1071 Don't raise error when trying to create another Qt app for Qt eventloop
  ipykernel/eventloops.py
  ipykernel/tests/test_eventloop.py
Labels: bug

#1067 Add api docs
  .github/workflows/ci.yml
  docs/api/ipykernel.comm.rst
  docs/api/ipykernel.inprocess.rst
  docs/api/ipykernel.rst
  docs/api/modules.rst
  docs/conf.py
  docs/index.rst
  ipykernel/comm/comm.py
  ipykernel/embed.py
  pyproject.toml
Labels: documentation

#1076 Fix Exception in OutStream.close()
  ipykernel/iostream.py
  ipykernel/tests/test_io.py
Labels: bug

#1055 Add copy_to_globals debug request handling
  ipykernel/debugger.py
  ipykernel/tests/test_debugger.py
  pyproject.toml
Labels: enhancement

#1078 Expose session start file in __file__.
  ipykernel/ipkernel.py
Labels: enhancement

#1080 Test spyder kernels
  .github/workflows/ci.yml
  .github/workflows/downstream.yml
Labels: maintenance

#1081 Maintenance updates
  ipykernel/eventloops.py
  ipykernel/inprocess/client.py
  ipykernel/kernelapp.py
  pyproject.toml
Labels: maintenance

#1082 Adopt more lint rules
  .pre-commit-config.yaml
  ipykernel/compiler.py
  ipykernel/connect.py
  ipykernel/eventloops.py
  ipykernel/inprocess/client.py
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/jsonutil.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/pickleutil.py
  ipykernel/serialize.py
  ipykernel/tests/test_eventloop.py
  ipykernel/tests/test_jsonutil.py
  ipykernel/tests/test_parentpoller.py
  pyproject.toml
Labels: maintenance
