Repository ipython/ipykernel, pull requests merged in 2024-10, with the labels that each got.

#1249 Kernel subshells (JEP91) implementation
  docs/api/ipykernel.rst
  ipykernel/control.py
  ipykernel/heartbeat.py
  ipykernel/iostream.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/shellchannel.py
  ipykernel/subshell.py
  ipykernel/subshell_manager.py
  ipykernel/thread.py
  ipykernel/zmqshell.py
  tests/test_ipkernel_direct.py
  tests/test_kernel_direct.py
  tests/test_message_spec.py
  tests/test_subshells.py
  tests/utils.py
Labels: enhancement

#1271 Detect parent change in more cases on unix
  ipykernel/kernelapp.py
  ipykernel/parentpoller.py
  tests/test_parentpoller.py
Labels: enhancement

#1273 Remove some potential dead-code.
  examples/embedding/inprocess_qtconsole.py
  ipykernel/kernelapp.py
  tests/test_eventloop.py
  tests/test_kernel.py
Labels: maintenance

#1281 socket must be None, not shell_socket for default shell
  ipykernel/kernelbase.py
Labels: bug

#1284 Drop support for Python 3.8
  .github/workflows/ci.yml
  pyproject.toml
Labels: maintenance

#1277 start testing on 3.13
  .github/workflows/ci.yml
  docs/conf.py
  ipykernel/_version.py
  ipykernel/debugger.py
  ipykernel/inprocess/channels.py
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/pickleutil.py
  ipykernel/thread.py
  pyproject.toml
Labels: maintenance

#1280 restore zero-copy recv on shell messages
  ipykernel/kernelbase.py
Labels: bug

#1285 Improve robustness of subshell concurrency tests
  tests/test_subshells.py
Labels: maintenance

#1282 remove deprecated ipyparallel methods now that they are broken anyway
  ipykernel/kernelbase.py
  tests/test_kernel_direct.py
Labels: maintenance

#1275 fix mixture of sync/async sockets in IOPubThread
  ipykernel/inprocess/ipkernel.py
  ipykernel/inprocess/socket.py
  ipykernel/iostream.py
  tests/test_io.py
  tests/test_kernel.py
Labels: maintenance
