Repository ipython/ipykernel, pull requests merged in 2024-03, with the labels that each got.

#1219 Allow datetime or str in test_sequential_control_messages
  pyproject.toml
  tests/test_kernel.py
Labels: bug

#1221 Update Release Scripts
  .github/workflows/prep-release.yml
  .github/workflows/publish-changelog.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#1079 Replace Tornado with AnyIO
  .github/workflows/ci.yml
  docs/api/ipykernel.inprocess.rst
  examples/embedding/inprocess_terminal.py
  ipykernel/control.py
  ipykernel/debugger.py
  ipykernel/eventloops.py
  ipykernel/inprocess/blocking.py
  ipykernel/inprocess/client.py
  ipykernel/inprocess/ipkernel.py
  ipykernel/inprocess/manager.py
  ipykernel/inprocess/session.py
  ipykernel/inprocess/socket.py
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/zmqshell.py
  pyproject.toml
  tests/conftest.py
  tests/inprocess/test_kernel.py
  tests/inprocess/test_kernelmanager.py
  tests/test_async.py
  tests/test_embed_kernel.py
  tests/test_eventloop.py
  tests/test_io.py
  tests/test_ipkernel_direct.py
  tests/test_kernel_direct.py
  tests/test_kernelapp.py
  tests/test_message_spec.py
  tests/test_pickleutil.py
Labels: enhancement

#1223 Do not import debugger/debugpy unless needed
  ipykernel/ipkernel.py
Labels: bug

#1224 Backport PR #1223 on branch 6.x (Do not import debugger/debugpy unless needed)
  ipykernel/ipkernel.py
Labels: maintenance
