Repository ipython/ipykernel, pull requests merged in 2024-02, with the labels that each got.

#1203 Do git ignore of /node_modules/.cache
  .gitignore
Labels: maintenance

#1204 fix: on exception, return a 0, so that the "sum" still computes
  ipykernel/kernelbase.py
Labels: bug

#1206 Fix: ipykernel_launcher, delete absolute sys.path[0]
  ipykernel_launcher.py
Labels: bug

#1207 Re-enable skipped debugger test
  tests/test_debugger.py
Labels: maintenance

#1208 Correct spelling mistake
  ipykernel/debugger.py
Labels: documentation

#1209 Unpin pytest-asyncio and update ruff config
  docs/conf.py
  hatch_build.py
  ipykernel/__init__.py
  ipykernel/compiler.py
  ipykernel/datapub.py
  ipykernel/debugger.py
  ipykernel/eventloops.py
  ipykernel/gui/gtk3embed.py
  ipykernel/gui/gtkembed.py
  ipykernel/ipkernel.py
  ipykernel/kernelspec.py
  ipykernel/pickleutil.py
  ipykernel/pylab/backend_inline.py
  ipykernel/pylab/config.py
  ipykernel/serialize.py
  pyproject.toml
Labels: maintenance

#1213 Disable frozen modules by default, add a toggle
  ipykernel/kernelspec.py
  tests/test_kernelspec.py
Labels: bug

#1214 Fix typings and update project urls
  ipykernel/zmqshell.py
  pyproject.toml
Labels: maintenance

#1212 Eventloop scheduling improvements for stop_on_error_timeout and schedule_next
  ipykernel/eventloops.py
  ipykernel/kernelbase.py
Labels: enhancement

#1210 Remove control queue
  ipykernel/inprocess/ipkernel.py
  ipykernel/kernelbase.py
  pyproject.toml
  tests/test_ipkernel_direct.py
  tests/test_kernel.py
Labels: enhancement

#1216 Fix side effect import for pickleutil
  ipykernel/pickleutil.py
Labels: bug

#1217 Fix side effect import for pickleutil
  ipykernel/pickleutil.py
Labels: bug
