Repository ipython/ipykernel, pull requests merged in 2024-01, with the labels that each got.

#1189 Pin pytest-asyncio to 0.23.2
  pyproject.toml
Labels: maintenance

#1191 Always set debugger to true in kernelspec
  ipykernel/kernelspec.py
  tests/test_debugger.py
Labels: enhancement

#1194 Revert "Enable `ProactorEventLoop` on windows for `ipykernel`"
  ipykernel/kernelapp.py
Labels: bug

#1186 Make outputs go to correct cell when generated in threads/asyncio
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/kernelbase.py
  tests/test_kernel.py
Labels: bug

#1200 Fix handling of "silent" in execute request
  ipykernel/kernelbase.py
Labels: bug
