Repository ipython/ipykernel, pull requests merged in 2025-03, with the labels that each got.

#1373 Fix OutStream using _fid before being defined
  ipykernel/iostream.py
Labels: bug

#1291 Use zmq-anyio
  docs/api/ipykernel.rst
  ipykernel/debugger.py
  ipykernel/heartbeat.py
  ipykernel/inprocess/ipkernel.py
  ipykernel/inprocess/session.py
  ipykernel/inprocess/socket.py
  ipykernel/iostream.py
  ipykernel/ipkernel.py
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
  ipykernel/shellchannel.py
  ipykernel/subshell.py
  ipykernel/subshell_manager.py
  ipykernel/trio_runner.py
  pyproject.toml
  tests/conftest.py
  tests/test_async.py
  tests/test_embed_kernel.py
  tests/test_eventloop.py
  tests/test_io.py
  tests/test_kernelapp.py
  tests/test_start_kernel.py
  tests/test_zmq_shell.py
Labels: enhancement

#1363 TQDM workaround due to unresponsive maintainer
  ipykernel/zmqshell.py
Labels: maintenance
