Repository ipython/ipykernel, pull requests merged in 2025-02, with the labels that each got.

#1314 More Informative assert
  tests/test_subshells.py
Labels: maintenance

#1321 Fix types lints
  ipykernel/subshell_manager.py
Labels: maintenance

#1327 Manually update mdformat pre-commit and run it.
  .pre-commit-config.yaml
  CHANGELOG.md
Labels: maintenance

#1328 Manually update Codespell and fix new errors.
  .pre-commit-config.yaml
  ipykernel/trio_runner.py
  tests/utils.py
Labels: maintenance

#1332 Remove dead code.
  tests/_asyncio_utils.py
  tests/test_eventloop.py
Labels: maintenance

#1305 properly close OutStream and various fixes
  ipykernel/_version.py
  ipykernel/embed.py
  ipykernel/inprocess/channels.py
  ipykernel/iostream.py
  ipykernel/kernelapp.py
  ipykernel/pickleutil.py
  ipykernel/thread.py
  tests/test_kernelapp.py
Labels: maintenance

#1326 Manually update pre-commit hooks that do not trigger new errors/fixes.
  .pre-commit-config.yaml
Labels: maintenance

#1317 Copy payloadpage.page from IPython
  ipykernel/zmqshell.py
Labels: maintenance

#1325 Try to force precommit-ci to send autoupdate PRs.
  .pre-commit-config.yaml
Labels: maintenance

#1318 Remove downstream_check
  .github/workflows/downstream.yml
Labels: maintenance

#1315 Remove implicit bind_kernel in `%qtconsole`
  ipykernel/zmqshell.py
Labels: bug

#1296 Use supported_features=['debugger'] in kernel info reply
  ipykernel/kernelbase.py
  tests/test_debugger.py
Labels: enhancement

#1300 Replace BaseThread's add_task with start_soon
  ipykernel/iostream.py
  ipykernel/kernelbase.py
  ipykernel/subshell_manager.py
  ipykernel/thread.py
Labels: enhancement

#1329 Some formatting changes to prepare bumping ruff pre-commit.
  examples/embedding/inprocess_qtconsole.py
  examples/embedding/inprocess_terminal.py
  examples/embedding/ipkernel_wxapp.py
  hatch_build.py
  ipykernel/__main__.py
  ipykernel/compiler.py
  ipykernel/connect.py
  ipykernel/datapub.py
  ipykernel/debugger.py
  ipykernel/embed.py
  ipykernel/gui/gtk3embed.py
  ipykernel/gui/gtkembed.py
  ipykernel/heartbeat.py
  ipykernel/inprocess/blocking.py
  ipykernel/inprocess/client.py
  ipykernel/inprocess/constants.py
  ipykernel/inprocess/socket.py
  ipykernel/log.py
  ipykernel/shellchannel.py
  ipykernel/trio_runner.py
  tests/test_zmq_shell.py
Labels: maintenance

#1331 Ignore or fix most of the remaining ruff 0.9.6 errors
  ipykernel/datapub.py
  pyproject.toml
Labels: maintenance

#1337 try to fix spyder kernel install
  .github/workflows/downstream.yml
Labels: maintenance

#1295 Suggest to make implementations of some function always return awaitable
  ipykernel/kernelbase.py
  pyproject.toml
Labels: maintenance, deprecate, api_change

#1343 Email is @python.org since 2018
  pyproject.toml
Labels: maintenance

#1335 Remove test_check job
  .github/workflows/ci.yml
Labels: maintenance

#1341 Enable ruff G002 and fix 6 occurences
  ipykernel/kernelapp.py
  pyproject.toml
Labels: maintenance

#1342 Remove unused ignores lints.
  pyproject.toml
Labels: maintenance

#1347 Pin sphinx to resolve docs build failures
  pyproject.toml
Labels: maintenance

#1334 Refine deprecation error messages.
  ipykernel/datapub.py
  ipykernel/log.py
  ipykernel/pickleutil.py
  ipykernel/serialize.py
Labels: maintenance

#1345 Try to debug non-closed iopub socket
  tests/test_connect.py
Labels: maintenance

#1322 Delete always skipped test, fix trio test, fix framelocal has not .clear()
  ipykernel/embed.py
  ipykernel/ipkernel.py
  ipykernel/kernelapp.py
  pyproject.toml
  tests/test_embed_kernel.py
  tests/test_ipkernel_direct.py
  tests/test_kernel_direct.py
  tests/test_kernelapp.py
Labels: maintenance

#1346 Make our own mock kernel methods async
  tests/conftest.py
Labels: maintenance

#1349 Disable 3 failing downstream tests, but keep testing the rest.
  .github/workflows/downstream.yml
  ipykernel/inprocess/client.py
  tests/test_subshells.py
Labels: maintenance

#1350 Try to reenable tests from downstream ipywidgets
  .github/workflows/downstream.yml
Labels: maintenance

#1324 Don't rerun test with --lf it hides failures.
  .github/workflows/ci.yml
  .readthedocs.yaml
  tests/test_eventloop.py
Labels: maintenance

#1340 Check ignores warnings are still relevant.
  pyproject.toml
Labels: maintenance

#1348 Licence :: * trove classifers are deprecated
  pyproject.toml
Labels: maintenance

#1353 Another try at tracking down ResourceWarning with tracemalloc.
  pyproject.toml
  tests/conftest.py
  tests/test_connect.py
  tests/test_ipkernel_direct.py
Labels: maintenance

#1338 Move mypy disablinging error codes on a per-file basis
  pyproject.toml
Labels: maintenance

#1354 Fix expected text depending on IPython version.
  tests/test_start_kernel.py
Labels: maintenance

#1366 Make kernelbase._eventloop_set event thread-safe
  ipykernel/kernelapp.py
  ipykernel/kernelbase.py
Labels: bug

#1352 Remove deprecated modules since 4.3 (2016).
  ipykernel/datapub.py
  ipykernel/pickleutil.py
  ipykernel/serialize.py
  tests/test_pickleutil.py
Labels: maintenance, deprecate, api_change
